"""admin

Revision ID: 21e29636913d
Revises: 
Create Date: 2023-12-27 22:45:38.431902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e29636913d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_page_id", 'page', ['page_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('page_id')

    op.create_table('_alembic_tmp_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('page_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='fk_page_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
