"""add page

Revision ID: 4ebb0c1c6a25
Revises: 21e29636913d
Create Date: 2023-12-27 22:52:42.975554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebb0c1c6a25'
down_revision = '21e29636913d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('page_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('page_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
