"""admin panel

Revision ID: 92788eb359b9
Revises: 33cee870a541
Create Date: 2023-12-24 22:17:11.958509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92788eb359b9'
down_revision = '33cee870a541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
