"""First  migration

Revision ID: cdf1f57ccc4c
Revises: f987f408e591
Create Date: 2023-12-21 15:09:34.585879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf1f57ccc4c'
down_revision = 'f987f408e591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
