"""First1  migration

Revision ID: ded43e0540f7
Revises: cdf1f57ccc4c
Create Date: 2023-12-21 15:15:58.867345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded43e0540f7'
down_revision = 'cdf1f57ccc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
